### ISSUE TITLE
新手求问一下怎么报错

### ISSUE THREAD

**Issue by github410117** [qq644531343/GaoDeMap#1]
用cocopods将AMapCloudMap、AMapNavi更新了，但是还是报错，说<AMapNaviKit/MAMapKit.h>
找不到，一共12个错误，希望指点一下怎么做，谢谢

**Comment by qq644531343** [comment]
https://github.com/qq644531343/GaoDeMap/releases/download/1.0/GaoDeMap.zip

直接下载这个， 然后解压后打开workspace即可
